- hosts: all
  gather_facts: no
  roles:
    - ssh
    - base-system
    - greeter
    - i3
    - i3status
    - nextcloud-client
    - zsh
    - communication
    - rambox
    - pdf
    - security
    - iptables
    - browsers
    - dns-over-tls
    - mullvad

- hosts: vms
  roles:
    - qemu-guest-agent

- hosts: lenovo_x240
  roles:
    - tlp

- hosts: usb_ssd
  roles:
    - tlp

- hosts: all
  roles:
    - cleanup
