- hosts: workstations
  roles:
    - base-system	# work in progress
    - greeter		# done
    - i3		# done
    - i3status		# done
    - nextcloud-client	# done
    - zsh		# done
    - communication	# done
    - rambox-os		# done
    - pdf		# done but could have security improvements / isolation
    - security		# done
    - iptables
    - browsers		# chromium only and plugins missing
#    - torbrowser	# ToDo
    - qemu-guest-agent	# ToDo
    - dns-over-tls	# done
    - mullvad
    - cleanup		# done
  vars:
    username: "null"
    interfaces:
      - enp1s0
