- hosts: all
  gather_facts: no
  roles:
    - ssh
    - base-system
#    - greeter
#    - i3
#    - i3status
    - sway
    - i3status
    - zsh
    - iptables
    - dns-over-tls
    - security
    - nextcloud-client-flatpak
    - communication
    - rambox
    - pdf
    - browsers
    - mullvad
    - pentesting
    - tor

- hosts: vms
  roles:
    - qemu-guest-agent

- hosts: lenovo_x240
  roles:
    - tlp
    - tlp-lenovo

- hosts: usb_ssd
  roles:
    - tlp

- hosts: all
  roles:
    - cleanup
