- name: Install unattended-upgrades and apt-listchanges
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - unattended-upgrades
    - apt-listchanges

- name: Copy /etc/apt/apt.conf.d/20auto-upgrades
  copy:
    src: "{{ role_path }}/files/20auto-upgrades"
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Copy /etc/apt/apt.conf.d/50unattended-upgrades
  copy:
      src: "{{ role_path }}/files/50unattended-upgrades"
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      owner: root
      group: root
      mode: '0644'

- name: Copy /etc/apt/listchanges.conf
  copy:
    src: "{{ role_path }}/files/listchanges.conf"
    dest: /etc/apt/listchanges.conf
    owner: root
    group: root
    mode: '0644'
