- name: Prevent NetworkManager from overwriting dns settings
  copy:
    src: "{{ role_path}}/files/NetworkManager.conf"
    dest: /etc/NetworkManager/NetworkManager.conf
    mode: '0644'

- name: Prevent dhcp client from overwriting dns servers
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^supersede.*domain-name-servers', line: 'supersede	domain-name-servers	127.0.0.1,127.0.0.1;' }

- name: Switch nameserver to stubby
  copy:
    src: "{{ role_path}}/files/resolv.conf"
    dest: /etc/resolv.conf
    mode: '0644'

- name: Restart NetworkManager
  systemd:
    state: restarted
    name: NetworkManager
