- name: Create Applications folder for AppImages
  file:
    path: "/home/{{ username }}/Applications"
    state: directory
    mode: '0755'

- name: Download rambox-os appimage
  get_url:
    url: "{{ rambox_url }}"
    dest: "/home/{{ username }}/Applications/Rambox-OS.AppImage"
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create ~/.local/bin
  file:
    path: "/home/{{ username }}/.local/bin"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Link rambox-os to ~/.local/bin/rambox-os
  file:
    src: "/home/{{ username }}/Applications/Rambox-OS.AppImage"
    dest: "/home/{{ username }}/.local/bin/rambox-os"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
