- name: Install zsh
  apt:
    name: zsh
    update_cache: no

- name: Cloning oh-my-zsh for {{ username }}
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest="/home/{{ username }}/.oh-my-zsh"
  become: true
  become_user: "{{ username }}"
  become_method: sudo

- name: Cloning oh-my-zsh for root
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest="/root/.oh-my-zsh"

- name: Set pam_shells.so sufficient
  lineinfile:
    path: /etc/pam.d/chsh
    regexp: '^auth.*required.*pam_shells.so'
    line: 'auth       sufficient   pam_shells.so'

- name: set zsh default shell for null
  shell: "chsh -s $(which zsh)"
  become: true
  become_user: "{{ username }}"
  become_method: sudo

- name: set zsh default shell for root
  shell: "chsh -s $(which zsh)"

- name: Set pam_shells.so required 
  lineinfile:
    path: /etc/pam.d/chsh    
    regexp: '^auth.*pam_shells.so'
    line: 'auth       required   pam_shells.so'

- name: Copy zshrc to get configuration for {{ username }}
  copy:
    src: "{{ role_path}}/files/.zshrc"
    dest: "/home/{{ username }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'

- name: Copy zshrc to get configuration for root
  copy:
    src: "{{ role_path}}/files/.zshrc"
    dest: "/root/.zshrc"
    mode: '0600'

- name: Add local bin path for {{ username }}
  lineinfile:
    path: "/home/{{ username }}/.zshrc"
    regexp: '^PATH='
    line: "PATH=$PATH:/home/{{ username }}/.local/bin"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add sbin pathes for root
  lineinfile:
    path: /root/.zshrc
    regexp: '^PATH='
    line: PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin

