- name: Install dnscrypt-proxy
  apt:
    name: dnscrypt-proxy

- name: enable dnscrypt-proxy service and ensure it is not masked
  systemd:
    name: dnscrypt-proxy
    enabled: yes
    masked: no

- name: Make sure dnscrypt-proxy service is running
  systemd:
    state: started
    name: dnscrypt-proxy

- name: Choose random resolver
  lineinfile:
    path: /etc/dnscrypt-proxy/dnscrypt-proxy.conf
    regexp: 'ResolverName.*'
    line: "ResolverName ns0.dnscrypt.is"
    state: present

- name: Replace nameserver in /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver.*'
    line: nameserver 127.0.2.1
    state: present
