- name: Install snapd
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - snapd

- name: refresh all snaps
  shell: snap refresh

- name: Install chromium
  snap:
    name:
      - chromium

- name: Copy Chromium desktop file
  copy:
    src: /var/lib/snapd/desktop/applications/chromium_chromium.desktop
    dest: "/home/{{username}}/Applications/dmenu/chromium.desktop"
    remote_src: yes
