- name: Create Applications directory if it does not exist
  file:
    path: "/home/{{username}}/Applications"
    state: directory
    mode: '0751'
    owner: "{{ username }}"
    group: "{{ username }}"


- name: Create a Applications/dmenu if it does not exist
  file:
    path: "/home/{{username}}/Applications/dmenu"
    state: directory
    mode: '0751'
    owner: "{{ username }}"
    group: "{{ username }}"
