- name: Put /tmp to ram
  lineinfile:
    path: /etc/fstab
    regexp: '/tmp'
    line: "tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777 0 0"
    create: yes

- name: Put /var/cache to ram
  lineinfile:
    path: /etc/fstab
    regexp: '/var/cache'
    line: "tmpfs /var/cache tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777 0 0"
    create: yes

- name: Put /var/log/apt to ram
  lineinfile:
    path: /etc/fstab
    regexp: '/var/log/apt'
    line: "tmpfs /var/log/apt tmpfs defaults,noatime 0 0"
    create: yes
