- name: "Allow user {{ username }} on host {{ hostname }} to shutdown, hibernate, suspend and reboot the system"
  lineinfile:
    path: /etc/sudoers
    line: "{{ username }} {{ inventory_hostname }} =NOPASSWD: {{ allowed_commands }}"
    create: yes
