- name: Touch /etc/sudoers.d/powermanagement
  file:
    path: /etc/sudoers.d/powermanagement
    state: touch

- name: "Allow user {{ username }} on host {{ hostname }} to shutdown, hibernate, suspend and reboot the system"
  lineinfile:
    mode: 0440
    path: /etc/sudoers.d/powermanagement
    regexp: '^{{ username }} ALL = NOPASSWD:'
    line: "{{ username }} ALL = NOPASSWD: {{ allowed_commands }}"
